In [3]:
import numpy as np

In [9]:
array=np.array([
    [12,23,56],
    [16,28,55],
])
reshapearray=array.reshape((3,2))
print(reshapearray)


[[12 23]
 [56 16]
 [28 55]]


In [ ]:
pixels=np.arange(36)
One_D=pixels.reshape((6,6))


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [18]:
marks = np.arange(60)
marks.reshape((20,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [28]:
image = np.arange(60)
image.reshape((5,4,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [30]:
import numpy as np

patients = np.arange(300)
patients = patients.reshape((50, 6))

first_patient = patients[0]

print(first_patient)

[0 1 2 3 4 5]


In [34]:
data = np.arange(300)
array1=data.reshape((30,5,2))
print(array1)



[[[  0   1]
  [  2   3]
  [  4   5]
  [  6   7]
  [  8   9]]

 [[ 10  11]
  [ 12  13]
  [ 14  15]
  [ 16  17]
  [ 18  19]]

 [[ 20  21]
  [ 22  23]
  [ 24  25]
  [ 26  27]
  [ 28  29]]

 [[ 30  31]
  [ 32  33]
  [ 34  35]
  [ 36  37]
  [ 38  39]]

 [[ 40  41]
  [ 42  43]
  [ 44  45]
  [ 46  47]
  [ 48  49]]

 [[ 50  51]
  [ 52  53]
  [ 54  55]
  [ 56  57]
  [ 58  59]]

 [[ 60  61]
  [ 62  63]
  [ 64  65]
  [ 66  67]
  [ 68  69]]

 [[ 70  71]
  [ 72  73]
  [ 74  75]
  [ 76  77]
  [ 78  79]]

 [[ 80  81]
  [ 82  83]
  [ 84  85]
  [ 86  87]
  [ 88  89]]

 [[ 90  91]
  [ 92  93]
  [ 94  95]
  [ 96  97]
  [ 98  99]]

 [[100 101]
  [102 103]
  [104 105]
  [106 107]
  [108 109]]

 [[110 111]
  [112 113]
  [114 115]
  [116 117]
  [118 119]]

 [[120 121]
  [122 123]
  [124 125]
  [126 127]
  [128 129]]

 [[130 131]
  [132 133]
  [134 135]
  [136 137]
  [138 139]]

 [[140 141]
  [142 143]
  [144 145]
  [146 147]
  [148 149]]

 [[150 151]
  [152 153]
  [154 155]
  [156 157]
  [158 159]]

 [[160 1

Question 10: Shopping Mall

Ek shopping mall mein

4 floors
Har floor mein 5 shops
Har shop mein 7 products

Tasks

Correct shape mein reshape karo.
Floor 2 ki sari shops print karo.
Floor 4 ki Shop 3 ke products print karo.
Product #5 ko har shop se print karo.
Shape verify karo

In [ ]:
mall = np.arange(140)
shape=mall.reshape((4,5,7))
print(shape)
floor2shops=shape[1,:]



[[[  0   1   2   3   4   5   6]
  [  7   8   9  10  11  12  13]
  [ 14  15  16  17  18  19  20]
  [ 21  22  23  24  25  26  27]
  [ 28  29  30  31  32  33  34]]

 [[ 35  36  37  38  39  40  41]
  [ 42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55]
  [ 56  57  58  59  60  61  62]
  [ 63  64  65  66  67  68  69]]

 [[ 70  71  72  73  74  75  76]
  [ 77  78  79  80  81  82  83]
  [ 84  85  86  87  88  89  90]
  [ 91  92  93  94  95  96  97]
  [ 98  99 100 101 102 103 104]]

 [[105 106 107 108 109 110 111]
  [112 113 114 115 116 117 118]
  [119 120 121 122 123 124 125]
  [126 127 128 129 130 131 132]
  [133 134 135 136 137 138 139]]]
