In [4]:
import numpy as np

marks = np.array([
    [
        [80, 75, 90, 85],
        [60, 70, 65, 72],
        [88, 91, 84, 90]
    ],

    [
        [77, 80, 79, 82],
        [55, 60, 58, 61],
        [95, 93, 97, 98]
    ]
])
print(marks.shape)


(2, 3, 4)


In [11]:
print(marks[0][0:1])
marks[:,0]
marks[:,:,0]
total=marks.sum(axis=2)
print(total)


[[80 75 90 85]]
[[330 267 353]
 [318 234 383]]


In [17]:
game = np.random.randint(0,101,(5,20,10))
game2=game[1,:,:]
print(game2)

[[19 49  4 33 88 40 31 26 36 40]
 [73 72 36 46  9 49 12 41 91  8]
 [41  3 39  9 99 70 91 52 93 84]
 [21 60 67 77 33 73  4 60 34 48]
 [63 38 56 20 56 27 56 16 23 74]
 [26 60 68 41 99  6 73 18 87 37]
 [85 81 90 99 97 18 76 79  9 86]
 [56 35 91 60 30 72 66 71 30 66]
 [19 63 70 58 72 41 71 43 42 50]
 [38 63 88 90  9 90 58 57 27 73]
 [56 88 24 12 44 26 13 24 97 33]
 [51 42 17 32 37 28 93 59 10  7]
 [73 18 37 21 70 26 22 24 97 53]
 [72 99 97 22 90 78 51 85 13 82]
 [66 45 55 31 22  6  6 11 45 37]
 [73 83 99 29 42 53 59 51 93  9]
 [72  8 60 47 77 97 92 24 11 21]
 [91 81 63 22 74 95 82 86 20 90]
 [58 81 47 58 84 98 51 67 10 44]
 [93 42 22  0 43  0 18 99 49 14]]


In [3]:
import numpy as np

area = np.array([1000, 1200, 1500, 1800, 2000])

mean = np.mean(area)
std = np.std(area)

normalized_area = (area - mean) / std

print("Mean:", mean)
print("Std:", std)
print("Standardized Area:", normalized_area)

Mean: 1500.0
Std: 368.7817782917155
Standardized Area: [-1.35581536 -0.81348922  0.          0.81348922  1.35581536]


In [ ]:
import numpy as np

salary = np.array([30000, 40000, 50000, 60000, 70000, 80000])


avrage=np.mean(salary)
std=np.std(salary)
print(avrage)
print(std)
zscore=(salary-avrage)/std
print(zscore) 

55000.0
17078.25127659933
[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
