# 📚 Day 13: NumPy - Array Reshaping & Advanced Operations

## Topics Covered:
- Importing NumPy
- Creating Arrays
- Reshaping Arrays (1D to 2D to 3D)
- Array Indexing
- Real-world Examples
- Shopping Mall Project

**Confidence Level:** 8/10 | **Time:** 2.5 hours

In [3]:
import numpy as np
print(f"NumPy Version: {np.__version__}")

## Array Reshaping

Reshaping changes the dimensions of an array without changing its data.

In [9]:
# Create and reshape array
array = np.array([
    [12, 23, 56],
    [16, 28, 55],
])

print("Original Array (2x3):")
print(array)

reshaped_array = array.reshape((3, 2))
print("\nReshaped Array (3x2):")
print(reshaped_array)

Original Array (2x3):
[[12 23 56]
 [16 28 55]]

Reshaped Array (3x2):
[[12 23]
 [56 16]
 [28 55]]


## 2D to 3D Reshaping

Multi-dimensional array for complex data structures

In [ ]:
# Create pixels array (1D)
pixels = np.arange(36)

# Reshape to 2D (6x6 image)
image_2d = pixels.reshape((6, 6))
print("2D Image (6x6):")
print(image_2d)

In [18]:
# Marks reshape to (20x3)
marks = np.arange(60)
marks_reshaped = marks.reshape((20, 3))
print("Marks Array (20x3):")
print(marks_reshaped[:5])  # Show first 5 rows

## 3D Reshaping (Color Images)

3D arrays are used for RGB images and video data

In [28]:
# 3D image (5x4x3) - 5 frames, 4x3 pixels, RGB
image = np.arange(60)
image_3d = image.reshape((5, 4, 3))
print("3D Image Shape:", image_3d.shape)
print("3D Image:")
print(image_3d)

## Array Indexing

Accessing elements from multi-dimensional arrays

In [30]:
# Patient data: 50 patients with 6 attributes each
patients = np.arange(300)
patients = patients.reshape((50, 6))

# Get first patient
first_patient = patients[0]
print(f"First patient: {first_patient}")

First patient: [0 1 2 3 4 5]


## 🏬 Project: Shopping Mall Structure

**Structure:**
- 4 floors
- 5 shops per floor
- 7 products per shop

**Total shape:** (4, 5, 7)

In [ ]:
# Shopping mall structure
mall = np.arange(140)
mall_shape = mall.reshape((4, 5, 7))

print("Mall Shape:", mall_shape.shape)
print("\nFloor 1 Shops:")
print(mall_shape[0])  # All shops on floor 1

print("\nFloor 3, Shop 2 Products:")
print(mall_shape[2][1])  # Floor 3, Shop 2

print("\nProduct 5 in Floor 2, Shop 3:")
print(mall_shape[1][2][4])  # Floor 2, Shop 3, Product 5

## Summary

✅ Imported NumPy
✅ Created arrays using arange()
✅ Reshaped 1D to 2D arrays
✅ Reshaped 2D to 3D arrays
✅ Practiced array indexing
✅ Built Shopping Mall system
✅ Understood multi-dimensional data

**Next Step:** Day 14 - NumPy Statistical Operations